spring:
  autoconfigure:
    exclude: org.springframework.ai.vectorstore.mongodb.autoconfigure.MongoDBAtlasVectorStoreAutoConfiguration
  data:
    mongodb:
      database: ExpenseTracker
      uri: ${DB_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  thymeleaf:
    cache: false

  openai:
    api:
      key: ${OPENAI_API_KEY}
      timeout: 60


server:
  port: 8080

# Optional: JWT and logging config
jwt:
  secret: b70cdb158c788402d4f4729a4d0a98a8da40c57b
  expiration: 3600000  # 1 hour in ms

logging:
  level:
    root: INFO
    com.expensetracker: DEBUG

